"""v2

Revision ID: 4298c831720a
Revises: 8dd7ef4f23cb
Create Date: 2023-08-03 21:44:45.930046

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4298c831720a'
down_revision = '8dd7ef4f23cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
