"""init

Revision ID: 6ef3db7db213
Revises: 
Create Date: 2023-08-03 20:36:20.128662

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6ef3db7db213'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gemproperties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('gem_clarity', sa.Integer(), nullable=True),
    sa.Column('gem_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('gem_types', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gem_properties_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gem_properties_id'], ['gemproperties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gem_id'), 'gem', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gem_id'), table_name='gem')
    op.drop_table('gem')
    op.drop_table('gemproperties')
    # ### end Alembic commands ###
