"""v2

Revision ID: 8dd7ef4f23cb
Revises: 6ef3db7db213
Create Date: 2023-08-03 21:32:50.810450

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8dd7ef4f23cb'
down_revision = '6ef3db7db213'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
