"""v1

Revision ID: eb6675fb54d9
Revises: 9c5e50425a00
Create Date: 2023-08-04 10:55:33.422753

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'eb6675fb54d9'
down_revision = '9c5e50425a00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
